theme:      jekyll-theme-cayman

title:      ☕️ Zero Meetings Proof 👌
tagline:    A new Blockchain Scalability Solution

author:
  name:       Raman Shalupau
  url:        https://ksaitor.com


google_analytics: UA-30171436-15
